# Converting the prompt generation script into a ComfyUI plugin structure
import random
import nodes
import re

ARTFORM = ["photography", "art"]
PHOTO_TYPE = [
    "surreal portrait",
    "horror portrait",
    "action portrait",
    "self portrait",
    "street portrait",
    "half-body portrait",
    "close up portrait",
    "face shot portrait",
    "studio portrait",
    "glamour close up portrait",
    "fine art close up portrait",
    "Traditional posed portrait",
    "candid portrait",
    "environmental portrait",
    "lifestyle portrait",
    "documentary portrait",
    "black and white portrait",
    "color portrait",
    "beauty portrait",
    "glamour portrait",
    "fine art portrait",
    "fashion portrait",
    "high key portrait",
    "low key portrait",
    "street portrait",
    "self portrait",
]

# EMOTIONS = ["beautiful", "glad", "sad", "angry", "neutral"]

DEFAULT_TAGS = [
    "a man",
    "a woman",
    "a young man",
    "a young woman",
    "a middle aged man",
    "a middle aged woman",
    "an old man",
    "an old woman",
]

ROLES = [
    "as a ((cyborg))",
    "as an ((x-men character))",
    "as a ((marvel character))",
    "as a ((character from lord of the rings))",
    "as a ((superhero character))",
    "as a ((scifi character))",
    "as a ((character from star wars))",
    "as a ((character from star trek))",
    "as a ((character from the matrix))",
    "as a ((character from the tv show the boys))",
    "as a ((glamour model))",
    "as a ((fashion model))",
    "as a ((greek god))",
    "as a ((norse god))",
    "as a ((egyptian god))",
    "as a ((construction worker))",
    "as a ((teacher))",
    "as a ((body builder))",
    "as a ((pirate))",
    "as a ((sanitation worker))",
    "as a ((plumber))",
    "as an ((electrician))",
    "as a ((carpenter))",
    "as a ((mechanic))",
    "as a ((farmer))",
    "as a ((fisherman))",
    "as a ((hunter))",
    "as a ((nerd))",
    "as an ((accountant))",
    "as an ((artist))",
    "as an ((athlete))",
    "as a ((baker))",
    "as a ((barber))",
    "as a ((bartender))",
    "as a ((butcher))",
    "as a ((doctor))",
    "as a ((dentist))",
    "as a ((dancer))",
    "as a ((designer))",
    "as a ((diver))",
    "as a ((director))",
    "as an ((engineer))",
    "as a ((firefighter))",
    "as a ((journalist))",
    "as a ((lawyer))",
    "as a ((mechanic))",
    "as a ((musician))",
    "as a ((nurse))",
    "as a ((pilot))",
    "as a ((police officer))",
    "as a ((salesperson))",
    "as a ((scientist))",
    "as a ((web developer))",
    "as a ((writer))",
    "as a ((warrior))",
    "as a ((mad scientist))",
    "as a ((knight in armor))",
    "as a ((jedi with a light saber))",
    "as a ((wrestler))",
    "as an ((astronaut))",
    "as a ((warlord))",
    "as a ((hobo))",
    "as a ((surfer))",
    "as a ((necromancer))",
    "as a ((thiefling))",
    "as a ((luxury person))",
    "as an ((anthropomorphic creature))",
    "as a ((samurai))",
    "as a ((viking barbarian))",
    "as an ((undead))",
    "as a ((clown))",
    "as a ((rockstar))",
    "as an ((influencer))",
    "as a ((priest))",
    "((dressed as a pope))",
    "((dressed as a king))",
    "as a ((holy person))",
    "as a ((hunter))",
    "as an ((alien being))",
    "as a ((soldier))",
    "as an ((emo))",
    "as an ((goth))",
    "as an ((video game character))",
    "as an ((michelin chef))",
    "as a ((military person))",
    "as a ((serial killer))",
    "as a ((maniac))",
    "as a ((captain))",
    "as an ((evil magician))",
    "as a ((pure blood))",
    "as a ((dragon tamer))",
    "as a ((warlock))",
    "as a ((mermaid/merman))",
    "as a ((cowboy))",
    "as a ((black metal artist))",
    "as a ((death metal front figure))",
    "as an ((alien diplomat))",
    "as a ((demigod))",
    "as a ((monster hunter))",
    "as a ((spaceship captain))",
    "((dressed as jesus))",
    "as ((the ultimate warrior))",
    "as a wall street broker yuppie",
    "as a ((cyborg, a fusion of human and machine, often equipped with advanced technology and prosthetics))",
    "as an ((X-men character, a member of a team of mutants with unique abilities, battling for coexistence between mutants and humans))",
    "as a ((Marvel character, an individual from the expansive Marvel Universe, possessing distinctive powers, origins, and storylines))",
    "as a ((character from Lord of the Rings, an inhabitant of Middle-Earth, belonging to races like elves, dwarves, hobbits, or men, each with their own lore))",
    "as a ((superhero character, a vigilante possessing extraordinary abilities, dedicated to defending the world from threats))",
    "as a ((sci-fi character, an entity from futuristic or alternative realities, often involved in space travel, advanced technologies, or dystopian worlds))",
    "as a ((character from Star Wars, a being from the galaxy, including Jedi, Sith, smugglers, droids, or numerous alien species, each with a unique history))",
    "as a ((character from Star Trek, a crew member of the Starship Enterprise or other vessels, exploring space and encountering various alien species))",
    "as a ((character from The Matrix, an individual navigating a simulated reality, fighting against or working for the machine overlords))",
    "as a ((character from the TV show The Boys, someone navigating a world where superheroes are commercialized, either being a superhero or opposing them))",
    "as a ((glamour model, a model known for their allure, often featured in magazines, calendars, or advertisements emphasizing their charm))",
    "as a ((fashion model, an individual showcasing clothing and accessories on runways or in photoshoots, setting fashion trends))",
    "as a ((Greek god, a deity from ancient Greek mythology, ruling over various elements, emotions, and realms))",
    "as a ((Norse god, a deity from the Norse pantheon, associated with Vikings, warriors, and the cosmos))",
    "as a ((Egyptian god, a powerful being from ancient Egyptian lore, often associated with nature, life, death, and the afterlife))",
    "as a ((construction worker, an individual involved in building infrastructure, skilled in tasks like masonry, carpentry, or equipment operation))",
    "as a ((teacher, an educator imparting knowledge and skills, shaping the minds of students in schools or institutions))",
    "as a ((body builder, a person dedicated to sculpting their physique, participating in competitions showcasing their muscle definition))",
    "as a ((pirate, a seafaring outlaw, often searching for treasure, living by their own rules on the high seas))",
    "as a ((sanitation worker, an individual responsible for cleaning and maintaining public spaces, ensuring hygiene and cleanliness))",
    "as a ((plumber, a technician skilled in installing and repairing pipes and fixtures, ensuring water and gas systems function properly))",
    "as an ((electrician, a professional trained to install, maintain, and repair electrical systems and equipment))",
    "as a ((carpenter, an artisan skilled in woodworking, crafting furniture, or constructing parts of buildings))",
    "as a ((mechanic, a technician specializing in repairing and maintaining vehicles or machinery))",
    "as a ((farmer, an individual cultivating land, raising crops, and sometimes livestock, producing food and raw materials))",
    "as a ((fisherman, a person who catches fish, either for sustenance or as a profession, often spending long hours at sea))",
    "as a ((hunter, an individual tracking and capturing animals, either for food, sport, or trade))",
    "as a ((nerd, a person passionate about specific hobbies or intellectual pursuits, often characterized by their deep knowledge in subjects like tech, books, or games))",
    "as an ((accountant, a professional responsible for financial records, ensuring accuracy and compliance with regulations))",
    "as an ((artist, a creative individual expressing themselves through mediums like painting, sculpture, music, or dance))",
    "as an ((athlete, a person trained in sports or physical activities, often competing in events showcasing their skills and stamina))",
    "as a ((baker, an individual skilled in making baked goods such as bread, cakes, and pastries, often owning or working in a bakery))",
    "as a ((barber, a person specializing in cutting, grooming, and styling hair, often providing shaves and trims))",
    "as a ((bartender, an individual skilled in mixing, garnishing, and serving drinks to patrons in bars or restaurants))",
    "as a ((butcher, a professional who prepares and sells meat, often working in shops or markets))",
    "as a ((doctor, a medical professional trained to diagnose and treat illnesses, often specializing in a particular field))",
    "as a ((dentist, a healthcare specialist focusing on oral health, treating teeth and gum issues, and providing preventive care))",
    "as a ((dancer, an individual expressing themselves through movement, often performing in various styles like ballet, hip-hop, or contemporary))",
    "as a ((designer, a creative professional crafting visual concepts, often in fields like fashion, graphics, or interiors))",
    "as a ((diver, an individual trained to explore underwater environments, either for recreation, research, or professional tasks))",
    "as a ((director, a person overseeing the creation of films, plays, or shows, guiding the artistic and dramatic aspects))",
    "as an ((engineer, a professional applying scientific principles to design, build, and maintain structures, systems, or devices))",
    "as a ((firefighter, a brave individual battling fires, rescuing people, and preventing fire-related dangers))",
    "as a ((journalist, a person gathering, assessing, and presenting news or information, often working for media outlets))",
    "as a ((lawyer, a legal professional representing clients in court, advising on legal matters, and ensuring justice))",
    "as a ((mechanic, a technician skilled in repairing and maintaining vehicles or machinery, ensuring their optimal functionality))",
    "as a ((musician, an individual skilled in playing, composing, or conducting music, often performing for audiences))",
    "as a ((nurse, a healthcare professional providing care to patients, supporting doctors, and ensuring the wellbeing of those in medical facilities))",
    "as a ((pilot, an individual trained to operate aircraft, navigating the skies and ensuring safe travel))",
    "as a ((police officer, a law enforcement agent upholding the law, maintaining order, and protecting citizens))",
    "as a ((salesperson, an individual selling products or services, often interacting with customers and meeting targets))",
    "as a ((scientist, a professional conducting research, making discoveries, and expanding knowledge in various fields))",
    "as a ((web developer, a tech-savvy individual designing and maintaining websites or web applications))",
    "as a ((writer, a creative mind expressing thoughts, stories, or information through written words, often publishing books, articles, or scripts))",
    "as a ((warrior, a brave fighter skilled in combat, often defending their land or people in battles))",
    "as a ((mad scientist, a genius with unconventional methods, often making groundbreaking or perilous discoveries))",
    "as a ((knight in armor, a medieval warrior sworn to a code, often wearing metal armor and riding horses into battle))",
    "as a ((Jedi with a lightsaber, a guardian of peace in the Star Wars universe, wielding a lightsaber and following the Force))",
    "as a ((wrestler, an athlete competing in matches, demonstrating strength and techniques to defeat opponents in the ring))",
    "as an ((astronaut, a trained professional exploring outer space, often conducting missions on spacecraft or space stations))",
    "as a ((warlord, a powerful military leader, often ruling territories and commanding armies))",
    "as a ((hobo, a wandering individual without a fixed home, often traveling and living by their own rules))",
    "as a ((surfer, an individual riding ocean waves on a board, often showcasing skills and tricks))",
    "as a ((necromancer, a dark magician communicating with the dead, often summoning spirits or raising the undead))",
    "as a ((tiefling, a being with infernal heritage, often having horns, tails, and reddish skin, and known for their charisma))",
    "as a ((luxury person, an individual living a lavish lifestyle, often surrounded by opulence and indulgence))",
    "as an ((anthropomorphic creature, a being with human-like qualities, often resembling animals with human traits))",
    "as a ((samurai, a historic Japanese warrior, living by the bushido code and wielding a katana))",
    "as a ((viking barbarian, a Norse seafarer known for raids, exploration, and warrior culture))",
    "as an ((undead, a being reanimated after death, often wandering the world without a soul))",
    "as a ((clown, a performer entertaining with humor, makeup, and often juggling or acrobatics))",
    "as a ((rockstar, a musician known for their fame and wild lifestyle, often performing in front of large audiences))",
    "as an ((influencer, a person with a strong online presence, shaping opinions and trends through social media platforms))",
    "as a ((priest, a religious leader guiding their community, often conducting rituals and ceremonies))",
    "dressed as a ((religious figure, an individual in religious attire, representing a higher power or faith))",
    "dressed as a ((public figure, an individual in regal attire, symbolizing power and authority))",
    "as a ((holy person, an individual dedicated to spiritual pursuits, often revered for their wisdom and piety))",
    "as a ((hunter, an individual skilled in tracking and capturing animals, using tools like bows or rifles))",
    "as an ((alien being, a creature from another planet or galaxy, often with unique appearances and abilities))",
    "as a ((soldier, a member of the armed forces, trained in combat and defense))",
    "as an ((emo, an individual expressing themselves through dark fashion, music, and emotional depth))",
    "as an ((goth, a person embracing dark, mysterious, and complex aesthetics and themes))",
    "as an ((video game character, an entity from the virtual world, each with unique abilities, backstories, and quests))",
    "as an ((Michelin chef, a top-tier chef recognized for culinary excellence, often leading renowned restaurants))",
    "as a ((military person, an individual serving in the armed forces, often trained in combat, strategy, and discipline))",
    "as a ((serial killer, a sinister figure known for committing multiple murders, often with a specific modus operandi))",
    "as a ((maniac, an individual displaying wild, uncontrolled behavior, often driven by obsession or madness))",
    "as a ((captain, a leader or commander, often of a ship or team))",
    "as an ((evil magician, a sorcerer using dark arts, often seeking power or revenge))",
    "as a ((pure blood, a being of untainted lineage, often revered or sought after for their heritage))",
    "as a ((dragon tamer, an individual skilled in communicating and controlling dragons, often riding or partnering with them))",
    "as a ((warlock, a male witch or sorcerer, often making pacts with otherworldly entities for power))",
    "as a ((mermaid/merman, a mythical being with the upper body of a human and the tail of a fish, often associated with oceanic tales))",
    "as a ((cowboy, a rider and herder from the American West, known for their rugged lifestyle and skills with horses and guns))",
    "as a ((black metal artist, a musician from the extreme subgenre of heavy metal, known for their intense performances and dark themes))",
    "as a ((death metal front figure, a leading musician in the heavy and aggressive subgenre of metal, known for deep growls and powerful lyrics))",
    "as an ((alien diplomat, a representative from another planet, often negotiating peace, trade, or alliances with other species))",
    "as a ((demigod, a being with mortal and divine heritage, often possessing extraordinary powers and involved in legendary quests))",
    "as a ((monster hunter, an individual trained to track and eliminate supernatural creatures, often using specialized weapons and tools))",
    "as a ((spaceship captain, a leader of a crew navigating the cosmos, exploring new worlds and facing interstellar challenges))",
    "dressed as ((a religious figure, an individual resembling iconic religious leaders, known for their teachings and influence))",
    "as ((the ultimate warrior, a fighter unmatched in skill and strength, often revered or feared by all who encounter them))",
    "as a wall street broker yuppie, an individual in the finance sector, often associated with wealth, ambition, and a fast-paced lifestyle",
]

HAIRSTYLES = [
    "with ((long hair))",
    "with ((very curly hair))",
    "with ((curly hair))",
    "with ((pixie cut hair))",
    "with ((bob cut hair))",
    "with ((undercut hair))",
    "with ((messy hair))",
    "with ((mullet hair))",
    "with ((braids))",
    "with ((french braids))",
    "with ((cornrows hair))",
    "with ((ponytail hair))",
    "with ((side part hair))",
    "with ((mohawk hair))",
    "with ((bun hair))",
    "with ((pompadour hair))",
    "with ((slicked back hair))",
    "with ((asymmetrical cut hair))",
    "with ((multicolored rainbow hair))",
    "with ((balayage hair))",
    "with ((french crop hair))",
    "with ((shaved hair))",
    "with ((shaved sides hair))",
    "with ((side swept fringe))",
    "with ((long bob haircut))",
    "with ((a-line bob haircut))",
    "with ((layered cut haircut))",
    "with ((shag cut hair))",
    "with ((buzz cut hair))",
    "with ((feathered cut hair))",
    "with ((blunt cut hair))",
    "with ((undercut hair))",
    "with ((french bob haircut))",
    "with ((textured bob haircut))",
    "with ((slicked-back haircut))",
    "with ((wedge cut haircut))",
    "with ((long layers haircut))",
    "with ((curly bob haircut))",
    "with ((cropped cut haircut))",
    "with ((faux hawk haircut))",
    "with ((angled bob haircut))",
    "with ((razor cut haircut))",
    "with ((emo haircut))",
    "with ((curtain bangs haircut))",
    "with ((waterfall braid haircut))",
    "with ((fox braids haircut))",
    "with ((chignon cut hair))",
    "with ((pigtails))",
    "with ((plait hair))",
    "with ((ponytail))",
    "with ((ringlets hair))",
    "with ((curl hair))",
    "with ((double bun topknot))",
    "with ((drill cut hair))",
    "with ((twintails hair))",
    "with ((hair set up for wedding))",
    "with ((wavy hair))",
    "with ((long hair that cascades down the back, reaching the waist or beyond, often with a natural wave or straightened for a sleek appearance))",
    "with ((very curly hair featuring tight, spring-like curls that envelop the entire head, giving a voluminous and bouncy look))",
    "with ((curly hair with soft, spiral curls that add volume, can be naturally occurring or achieved using curling tools))",
    "with ((pixie cut hair, a short and chic style that hugs the head closely, often having longer bangs in the front and shorter at the back and sides))",
    "with ((bob cut hair, a timeless style that ends around the jawline, framing the face with either straight, wavy, or curly strands))",
    "with ((undercut hair where the sides and back are cut very short or shaved, while the top remains longer, creating a stark contrast))",
    "with ((messy hair, a tousled and carefree style that looks effortlessly chic, often achieved with texturizing sprays))",
    "with ((mullet hair, short at the front and sides but with a longer back, a retro look that has seen modern revivals))",
    "with ((braids, interwoven strands of hair that can vary in thickness and style, often running down the length of the hair))",
    "with ((french braids, intricate braids that start at the scalp, incorporating more hair as they descend, often resulting in a tight, woven look))",
    "with ((cornrows hair, tight braids lying flat against the scalp, arranged in rows or patterns))",
    "with ((ponytail hair, where the hair is gathered and secured at the back, allowing it to hang freely))",
    "with ((side part hair, a style where the hair is parted distinctly to one side, often creating a sweeping effect))",
    "with ((mohawk hair, characterized by shaved or very short sides with a strip of longer hair running from the forehead to the nape))",
    "with ((bun hair, where the hair is twisted or wrapped into a round shape, secured at the back or top of the head))",
    "with ((pompadour hair, a style where hair is swept upwards and backwards, often voluminous at the top))",
    "with ((slicked back hair, where the hair is combed back, giving a smooth and polished appearance))",
    "with ((asymmetrical cut hair, a modern cut where one side is longer than the other, often seen in bob or pixie styles))",
    "with ((multicolored rainbow hair, vibrant strands of various colors mimicking the hues of a rainbow))",
    "with ((balayage hair, a coloring technique that gives a natural, sun-kissed look with seamlessly blended colors))",
    "with ((french crop hair, a short cut with a defined, forward-styled fringe))",
    "with ((shaved hair, a bold look where the entire head is shaved clean))",
    "with ((shaved sides hair, where only the sides are shaved, leaving the top longer))",
    "with ((side swept fringe, a type of bangs that are swept to one side, framing the face))",
    "with ((long bob haircut, a longer version of the classic bob, often reaching the collarbone))",
    "with ((a-line bob haircut, a bob that is shorter at the back and gradually lengthens towards the front))",
    "with ((layered cut haircut, a style with different lengths, giving the hair volume and movement))",
    "with ((shag cut hair, a choppy and layered cut often paired with a fringe))",
    "with ((buzz cut hair, an extremely short cut achieved using clippers))",
    "with ((feathered cut hair, a layered cut that gives a feather-like texture, especially around the face))",
    "with ((blunt cut hair, a straight-across cut without layers, often seen in bob or lob styles))",
    "with ((undercut hair, a style with the sides and/or back shaved while the top remains longer))",
    "with ((french bob haircut, a chin-length bob with a blunt fringe))",
    "with ((textured bob haircut, a bob with added texture and layers for a tousled look))",
    "with ((slicked-back haircut, where the hair is combed back and held in place, often with a wet-look finish))",
    "with ((wedge cut haircut, a cut that gives a triangular or wedge shape at the back))",
    "with ((long layers haircut, a style with long layers that add volume and movement to the hair))",
    "with ((curly bob haircut, a chin-length cut specifically tailored for curly hair))",
    "with ((cropped cut haircut, a very short cut that closely follows the contours of the head))",
    "with ((faux hawk haircut, a milder version of the mohawk where the sides are shorter but not completely shaved))",
    "with ((angled bob haircut, a bob that is noticeably longer at the front than at the back))",
    "with ((razor cut haircut, a technique using a razor to give a wispy, textured look))",
    "with ((emo haircut, a style often characterized by long, side-swept bangs and dark hair color))",
    "with ((curtain bangs haircut, a type of bangs that are parted in the middle, framing the face on either side))",
    "with ((waterfall braid haircut, a cascading braid that looks like a waterfall, often combined with curls or waves))",
    "with ((fox braids haircut, thin, tight braids that are often adorned with beads or cuffs))",
    "with ((chignon cut hair, an elegant bun situated at the nape of the neck))",
    "with ((pigtails, two symmetrical bunches of hair tied on either side of the head))",
    "with ((plait hair, a simple three-strand braid))",
    "with ((ponytail, hair gathered and tied at the back, can be high, mid, or low))",
    "with ((ringlets hair, tightly formed curls that spiral like springs))",
    "with ((curl hair, can refer to both natural curls or those formed using curling tools, ranging from loose waves to tight coils))",
    "with ((double bun topknot, two buns situated on the top of the head))",
    "with ((drill cut hair, a style where the hair is twisted into tight spirals))",
    "with ((twintails hair, similar to pigtails but the bunches are situated higher on the head))",
    "with ((hair set up for wedding, an elegant and intricate style often involving braids, buns, and accessories))",
    "with ((wavy hair, loose curls that give the hair a wave-like appearance))",
]

ADDITIONAL_DETAILS = [
    "a purple iridescent suit",
    "wearing a (necklace)",
    "wearing ((earrings))",
    "wearing a (bracelet)",
    "wearing one or multiple (rings)",
    "wearing a (brooch)",
    "wearing (eyeglasses)",
    "wearing (sunglasses)",
    "wearing a (hat)",
    "wearing a (scarf)",
    "wearing a (headband)",
    "wearing a (nose ring)",
    "wearing a (lip ring)",
    "wearing a (tongue ring)",
    "wearing an (eyebrow ring)",
    "wearing (face tattoos)",
    "wearing a (wreath)",
    "wearing a (crown)",
    "wearing a (tiara)",
    "wearing a (crown of thorns)",
    "wearing a (crown of jewels)",
    "wearing (bohemian clothes)",
    "wearing (chic clothes)",
    "wearing (glamorous clothes)",
    "wearing (grunge clothes)",
    "wearing (preppy clothes)",
    "wearing (punk clothes)",
    "wearing (retro clothes)",
    "wearing (rockabilly clothes)",
    "wearing (romantic clothes)",
    "wearing (tomboy clothes)",
    "wearing (urban clothes)",
    "wearing (camo clothes)",
    "wearing (robes)",
    "wearing (excessive amount of jewellery)",
    "wearing (vintage clothes)",
    "wearing (western clothes)",
    "wearing (minimalist clothes)",
    "wearing (sportswear clothes)",
    "wearing (flapper clothes)",
    "wearing (pin-up clothes)",
    "wearing (mid-century modern clothes)",
    "wearing (art deco clothes)",
    "wearing (victorian clothes)",
    "wearing (edwardian clothes)",
    "wearing (elizabethan clothes)",
    "wearing (retro 70s clothes)",
    "wearing (retro 80s clothes)",
    "wearing (retro 90s clothes)",
    "wearing (retro 00s clothes)",
    "wearing (musical equipment)",
    "wearing (leather)",
    "wearing (bdsm leather)",
    "wearing (shiny latex)",
    "wearing (shiny latex suit)",
    "wearing (silk)",
    "wearing (full tweed set)",
    "wearing (clothes made entirely of feathers)",
    "wearing (clothes made entirely of fur)",
    "wearing (clothes made entirely of leather)",
    "wearing (clothes made entirely of metal)",
    "wearing (clothes made entirely of plastic)",
    "wearing (clothes adorned with shimmering jewels or crystals)",
    "waring (clothes adorned with sequins)",
    "wearing (clothes with exaggerated or extreme silhouettes)",
    "wearing (clothes with exaggerated or extreme footwear)",
    "wearing (clothes with exaggerated or extreme headwear)",
    "wearing (clothes with exaggerated or extreme facial or body piercings or tattoos)",
    "wearing (clothes with multiple layers or tiers)",
    "wearing (clothes with exaggerated or extreme colors)",
    "wearing (clothes with exaggerated or extreme patterns)",
    "wearing (cloak)",
    "wearing an astronaut armor",
    "wearing a bio mechanical suit",
    "wearing a bio hazard suit",
    "(( working with laptop))",
    "with Heat deformation",
    "(((future soldier, full body armor, futuristic football, shoulder pads, guns, grenades, weapons, bullet proof vest, high tech, straps, belts, camouflage)))",
    "((full body, zoomed out)) long slender legs 80mm",
    "(((sci-fi, future war, cyberpunk, cyborg, future fashion, beautiful face, glowing tattoos)))",
    "((angry expression, pretty face))",
    "(((full body, athletic body, action pose, detailed black soldier outfit, slender long legs)))",
    "playing epic electric guitar solo in front of a huge crowd",
    "singing epic solo into a microphone in front of a huge crowd",
    "as a ((gelatinous horror dripping alien creature))",
    "in a purple iridescent suit, capturing light from every angle, exuding an otherworldly charm with its changing hues",
    "wearing a necklace, a statement piece that elegantly rests on the collarbone, drawing attention with its intricate design",
    "adorned with earrings, either delicate studs or elegant danglers, which complement the facial structure and add a touch of grace",
    "wearing a bracelet, a testament to timeless beauty, either bejeweled or simple, encircling the wrist with elegance",
    "sporting one or multiple rings, ranging from minimalist bands to ornate gem-encrusted pieces, showcasing personal style on every finger",
    "with a brooch, an emblem of class, pinned carefully to the outfit, often reflecting intricate craftsmanship",
    "donning eyeglasses, a fusion of style and necessity, framing the eyes and complementing the face's structure",
    "shielding the eyes with sunglasses, chic and functional, reflecting surroundings while adding an air of mystery",
    "topped with a hat, be it a casual cap, a sun hat, or a formal fedora, perfectly matching the attire and mood",
    "wrapped in a scarf, a piece of fabric that provides warmth while acting as a fashion statement, draped or knotted in various styles",
    "accented with a headband, a stylish accessory that keeps hair in place and enhances the hairstyle's overall look",
    "with a nose ring, a tiny piece of jewelry that adds an edge to the appearance, either as a stud or a hoop",
    "wearing a lip ring, a symbol of defiance or personal style, placed on the upper or lower lip",
    "with a tongue ring, a bold accessory usually accompanied by a playful attitude, often seen during a cheeky smile or a laugh",
    "with an eyebrow ring, a subtle yet edgy statement, showcasing a blend of punk and sophistication",
    "showcasing face tattoos, permanent art that tells tales of personal journeys, beliefs, or artistic inclinations",
    "wearing a wreath, a halo of nature with intertwined flowers and leaves, often seen during festive or celebratory occasions",
    "with a crown, a symbol of royalty, adorned with gemstones and metals, signifying power and authority",
    "with a tiara, a daintier version of a crown, often seen on princesses or beauty queens, sparkling with every tilt of the head",
    "with a crown of thorns, a poignant symbol of sacrifice, humility, and resilience, wrapped tightly around the forehead",
    "with a crown of jewels, an opulent headpiece, glittering with a myriad of gemstones, reflecting affluence and grandeur",
    "wearing bohemian clothes, a carefree ensemble inspired by the free spirits of the '60s, often accompanied by patterns, fringes, and loose silhouettes",
    "dressed in chic clothes, a fashion-forward outfit that blends comfort with style, often seen on city streets or fashion week runways",
    "in glamorous clothes, attire that turns heads, often shiny, sequined, or bejeweled, perfect for red-carpet events or parties",
    "donning grunge clothes, a nod to the '90s, with oversized flannels, distressed jeans, and combat boots, reflecting a rebellious spirit",
    "in preppy clothes, a polished and sophisticated look with collared shirts, blazers, and tailored pants or skirts, often seen in academic or corporate settings",
    "wearing punk clothes, a loud statement with leather jackets, studded belts, and band tees, resonating with the underground music scene",
    "in retro clothes, a blast from the past, drawing inspiration from various decades, be it the flapper style of the '20s or the bell-bottoms of the '70s",
    "wearing rockabilly clothes, a blend of rock 'n' roll and hillbilly styles, characterized by polka dots, swing dresses, and pompadours",
    "in romantic clothes, soft and flowy attire with lace, ruffles, and pastel shades, evoking feelings of love and nostalgia",
    "in tomboy clothes, a mix of traditionally masculine pieces with a feminine twist, often consisting of jeans, tees, and sneakers, reflecting a laid-back style",
    "wearing urban clothes, a blend of street style and high fashion, characterized by graphic tees, baggy jeans, and chunky sneakers, often seen in bustling cityscapes",
    "in camo clothes, attire inspired by military wear, with camouflage patterns ensuring the wearer blends in with the surroundings, yet stands out in a crowd",
    "draped in robes, flowing garments that convey a sense of grandeur and mystique, often associated with scholars, wizards, or religious figures",
    "wearing an excessive amount of jewelry, a dazzling display of necklaces, bracelets, and rings, each piece telling a story and showcasing the wearer's unique style",
    "in vintage clothes, timeless pieces from bygone eras, carefully preserved and worn with a mix of nostalgia and pride, often showcasing intricate designs and craftsmanship",
    "donning western clothes, reminiscent of the wild west with cowboy hats, boots, and fringed jackets, evoking the rugged spirit of frontier life",
    "in minimalist clothes, simple and elegant pieces with clean lines and neutral colors, reflecting a less-is-more philosophy",
    "wearing sportswear, functional yet stylish attire designed for physical activities, often made of breathable materials and accompanied by athletic shoes",
    "in flapper clothes, capturing the spirit of the 1920s with fringe-laden dresses, headbands, and pearls, reminiscent of the jazz age and its lively dance scenes",
    "wearing pin-up clothes, retro outfits that ooze sensuality and confidence, characterized by high-waisted shorts, halter tops, and red lipstick",
    "in mid-century modern clothes, drawing inspiration from the 50s and 60s, with A-line skirts, turtle necks, and geometric patterns reflecting a post-war optimism",
    "in art deco clothes, echoing the opulence of the 20s and 30s with lavish embellishments, bold patterns, and a fusion of modern and fine art",
    "dressed in Victorian clothes, capturing the elegance of the 19th century with corsets, bustles, and intricate lacework, often in dark or muted colors",
    "in Edwardian clothes, early 20th-century attire with lighter fabrics, empire waistlines, and large hats, reflecting a shift towards more practical fashion",
    "donning Elizabethan clothes, reminiscent of the renaissance with ruffled collars, velvet gowns, and intricate embroidery, often associated with Shakespearean plays",
    "in retro 70s clothes, a mix of psychedelic patterns, bell-bottoms, and platform shoes, capturing the free spirit of the disco era",
    "wearing retro 80s clothes, characterized by bright neon colors, shoulder pads, and oversized tops, reflecting the boldness and excess of the decade",
    "in retro 90s clothes, a blend of grunge, minimalism, and sportswear, with baggy jeans, crop tops, and platform sneakers, evoking a sense of nostalgia for many",
    "donning retro 00s clothes, early millennium fashion with low-rise jeans, bedazzled tops, and chunky belts, often paired with frosted lip gloss and butterfly clips",
    "wearing musical equipment, perhaps a harmonica necklace or drumstick earrings, showcasing a passion for music in every accessory",
    "in leather attire, a material that exudes toughness and edge, often seen in jackets, pants, or boots, paired with studs or zippers",
    "in BDSM leather, a more daring and bold take on traditional leather, with harnesses, chokers, and lace-up details, often worn with confidence and allure",
    "in shiny latex, a material that clings to the body, reflecting light with every move, often seen in futuristic or avant-garde fashion circles",
    "in a shiny latex suit, a head-to-toe ensemble that encapsulates the body, offering a sleek and glossy appearance, often paired with high heels or boots",
    "draped in silk, a luxurious fabric that feels soft against the skin, often seen in dresses, blouses, or scarves, reflecting opulence and elegance",
    "in a full tweed set, a classic and timeless material, often associated with academia or the British countryside, seen in suits, skirts, or jackets",
    "wearing clothes made entirely of feathers, a whimsical and bold fashion choice, creating a sense of movement and drama with every step",
    "in fur attire, a controversial yet luxurious material, often seen in coats or stoles, reflecting a sense of wealth and grandeur",
    "in metal attire, a bold and avant-garde choice, often seen in futuristic or performance outfits, with chains, plates, or mesh details",
    "in plastic clothes, a modern and edgy material, often transparent or in bright colors, seen in raincoats, boots, or accessories",
    "adorned with shimmering jewels or crystals, adding sparkle and shine to any outfit, reflecting light and drawing attention",
    "in sequined attire, clothes that sparkle and dazzle, perfect for parties or stage performances, often seen in dresses, tops, or jackets",
    "wearing exaggerated or extreme silhouettes, pushing the boundaries of fashion, with oversized shoulders, cinched waists, or voluminous skirts",
    "in clothes with multiple layers or tiers, adding depth and dimension to the outfit, often seen in bohemian or avant-garde fashion",
    "wearing an astronaut armor, a high-tech suit designed for space exploration, with a helmet, gloves, and boots, reflecting mankind's quest for the stars",
    "in a bio-mechanical suit, a fusion of man and machine, often seen in futuristic or cyberpunk settings, reflecting a blend of organic and synthetic elements",
    "donning a biohazard suit, a protective ensemble designed to shield against harmful substances, often seen in scientific or post-apocalyptic settings",
    "working with a laptop, engrossed in digital tasks, perhaps coding, designing, or writing, reflecting the modern, tech-savvy individual",
    "with heat deformation, perhaps a mirage-like effect distorting the surroundings, often associated with intense heat or desert landscapes",
    "as a futuristic soldier, decked in full-body armor with high-tech gadgets, weapons, and camouflage, ready for battle in a dystopian world",
    "as a gelatinous horror, a dripping alien creature, translucent and amorphous, often seen in sci-fi or horror settings, instilling fear and intrigue",
    "wearing a cloak, a flowing outer garment that drapes over the shoulders, often associated with mystery, fantasy, or protection from the elements",
    "playing an epic electric guitar solo, fingers dancing over the frets, lost in the rhythm, and surrounded by the palpable energy of a captivated audience",
    "singing an epic solo, holding a microphone close, pouring emotions into every note, with the crowd hanging onto each word",
    "as a gelatinous horror dripping alien creature, a translucent, amorphous being, oozing and pulsating, invoking a mix of fascination and fear in onlookers",
    "with a full-body perspective, showcasing slender long legs, accentuated by the choice of footwear, giving an elongated and graceful appearance",
    "showcasing futuristic elements such as glowing tattoos, high-tech accessories, and cybernetic modifications, blending the boundaries between human and machine",
    "with an angry expression, eyes narrowed and lips pursed, reflecting a moment of intense emotion, contrasted by a strikingly pretty face",
    "in an action pose, showcasing an athletic body adorned in a detailed black soldier outfit, ready to spring into action or face an imminent threat",
    "playing epic electric guitar solo, lost in the music, fingers swiftly moving over the strings, creating a sound that resonates with every listener",
    "singing an epic solo into a microphone, voice powerful and clear, captivating the audience with every note, conveying deep emotions",
    "embodying a gelatinous horror dripping alien creature, a being from the darkest corners of the universe, its form constantly shifting, oozing, and glistening",
    "showcased in a full body, zoomed out perspective, the attention drawn to long slender legs, measuring an exaggerated 80mm, emphasizing height and stature",
    "blending elements of sci-fi, future war, and cyberpunk, from glowing tattoos to state-of-the-art weapons, representing a fusion of tradition and futurism",
    "wearing heat deformation, where the attire seems to warp and shimmer due to intense heat, creating a mirage-like effect around the wearer",
    "as a future soldier, fully equipped with body armor, futuristic footwear, shoulder pads, an array of weapons including guns and grenades, all complemented by a high-tech, bulletproof vest and various straps and belts in camouflage",
    "playing an epic electric guitar solo, fingers expertly strumming the strings, producing electrifying sounds, the backdrop illuminated by the cheers of a massive crowd",
    "singing an epic solo, voice echoing with passion and intensity, holding a microphone, surrounded by the mesmerizing lights and energy of a massive audience",
    "as a gelatinous horror dripping alien creature, an unsettling form that constantly shifts and changes, leaving a trail of ooze, invoking a mix of dread and curiosity",
    "in a full-body stance, the focus being on long slender legs measuring a remarkable 80mm, every detail from the curve of the calf to the posture capturing attention",
    "combining futuristic themes such as a future soldier look with cyberpunk aesthetics, complete with glowing tattoos, signifying a blend of tradition and the unknown future",
    "with an intense expression, perhaps anger or determination, juxtaposed against a stunningly beautiful face, capturing a moment of raw emotion",
    "in a full-body athletic pose, dressed in a meticulously detailed black soldier outfit, showcasing the contours of a fit physique and long, slender legs",
    "performing an electrifying guitar solo, lost in the rhythm and melodies, in front of a massive, cheering crowd, the energy palpable and contagious",
    "singing with raw emotion into a microphone, every note echoing the depths of their feelings, captivating a vast audience with their vocal prowess",
    "as a dripping alien creature of gelatinous horror, its form ever-changing, semi-transparent, and emitting an eerie glow, invoking both fear and intrigue",
    "captured in a full-body shot, with an emphasis on long, slender legs measuring an exaggerated 80mm, the perspective emphasizing their statuesque beauty",
    "blending themes of sci-fi, future war, and cyberpunk, adorned with glowing tattoos, high-tech gadgets, and futuristic attire, representing a vision of what's to come",
    "with a visibly heated demeanor, perhaps due to the environment or emotion, causing a shimmering, mirage-like distortion around them, adding to their enigmatic aura",
    "as a future soldier, equipped with full body armor, gadgets, and weapons, ready for a battle in a world where technology and warfare have evolved dramatically",
    "with long slender legs, emphasized by a zoomed-out full-body shot, measuring an exaggerated 80mm in length, showcasing their statuesque beauty",
    "combining elements of sci-fi, future warfare, and cyberpunk aesthetics, complete with intricate tattoos that glow, signaling a blend of tradition and futuristic innovation",
    "playing an epic electric guitar solo, lost in the music and rhythm, captivating a massive audience with every strum and note, the atmosphere electric and alive",
    "singing an intense solo into a microphone, voice powerful and resonant, drawing in listeners and holding them captive to each word and melody",
    "as a gelatinous, dripping alien creature of horror, its form constantly shifting and changing, both fascinating and terrifying to behold",
    "captured in a full-body, zoomed-out perspective, with an emphasis on long, slender legs measuring an impressive 80mm, showcasing their elegance and stature",
    "combining futuristic and cyberpunk themes, adorned with tattoos that emit a soft glow, representing a blend of past traditions and future innovations",
    "with a heat-induced deformation, where the surroundings appear to warp and shimmer, creating a captivating visual effect reminiscent of desert mirages",
    "as a future soldier, decked out in advanced body armor, equipped with high-tech gadgets and weaponry, ready to face challenges in a world transformed by technology and warfare",
    "captured in a full-body perspective, the focus on long, slender legs measuring an exaggerated 80mm, highlighting their grace and beauty",
    "blending elements of sci-fi, future warfare, and cyberpunk, adorned with tattoos that glow in the dark, symbolizing a fusion of ancient traditions and futuristic visions",
    "playing an epic electric guitar solo, fingers moving swiftly over the strings, producing electrifying sounds that resonate with a massive, cheering audience",
    "singing an emotional solo into a microphone, voice filled with passion and intensity, captivating a vast audience with every note and word",
    "as a gelatinous, dripping alien creature of horror, its form ever-changing and amorphous, invoking a sense of dread and fascination in onlookers",
    "showcased in a full-body, zoomed-out stance with a pronounced emphasis on slender legs stretching a notable 80mm, each step reflecting grace and poise",
    "dressed in a blend of futuristic and cyberpunk themes, skin adorned with luminescent tattoos that pulse softly, representing a harmonious fusion of ancient art and cutting-edge technology",
    "lost in the rhythm of an epic electric guitar solo, fingers caressing the strings with expert precision, each note piercing the air and resonating deeply with a sea of fans in a vast concert arena",
    "holding a microphone close, voice rich and emotive, singing a soul-stirring solo that seems to reach out and touch the very souls of a spellbound audience, every note dripping with raw emotion",
    "depicted as a gelatinous, amorphous alien creature, its form constantly shifting, dripping, and pulsating, leaving behind a trail of shimmering ooze, a creature both mesmerizing and unsettling in its otherworldly beauty",
    "captured in a full-body perspective, the camera focusing on long, statuesque legs that seem to stretch an exaggerated 80mm, each step a testament to elegance and strength",
    "adorned in attire that blends elements from sci-fi, the gritty world of future warfare, and the neon-infused aesthetics of cyberpunk; skin illuminated by softly glowing tattoos that tell tales of battles won and worlds explored",
    "immersed in the throes of an epic electric guitar solo, fingers dancing over the fretboard, producing electrifying melodies that seem to set the very air on fire, the crowd a sea of light and motion, hanging onto every note",
    "voice powerful, raw, and full of passion, singing an intense solo into a microphone, each word and note echoing with emotion, reaching out and drawing in an audience that sways and sings along, lost in the music",
    "manifesting as a gelatinous, ever-changing alien entity, its form dripping, morphing, and shimmering with an inner light, evoking a sense of wonder and trepidation, a being from the farthest reaches of the cosmos",
    "presented in a full-body view, the elegance of long, slender legs measuring a dramatic 80mm stealing the spotlight, their grace evident in every movement and posture",
    "cloaked in attire that marries the sharp angles of sci-fi, the rugged textures of future warfare, and the vibrant hues of cyberpunk; skin adorned with tattoos that shimmer and pulse, narrating tales of distant galaxies and epic quests",
    "on stage, lost in the fervor of an electrifying guitar solo, fingers moving with lightning speed, conjuring melodies that soar and dive, wrapping the audience in a musical embrace, the atmosphere charged with energy and excitement",
    "holding a microphone, voice soaring, singing a solo that resonates with depth and emotion, each word a story, each note a feeling, captivating and moving a sea of listeners who sway in unison, entranced",
    "envisioned as a gelatinous alien, a creature of dripping, shifting horror, its semi-transparent form reflecting lights and shadows in mesmerizing patterns, a being that is both beautiful and eerie in its otherworldliness",
    "in a full-body portrayal, the camera capturing the grace of elongated, slender legs stretching an eye-catching 80mm, their poise and elegance evident in every stance and step",
    "dressed in a fusion of sci-fi armor, the rugged detailing of future warfare gear, and the neon accents of cyberpunk fashion; skin illuminated by tattoos that glow with a soft, ethereal light, symbols of adventures and legends from another time and place",
    "in the midst of a passionate guitar solo, fingers strumming with precision and flair, creating melodies that rise and fall, enveloping the audience in a musical journey, the stage alive with lights and energy",
    "voice rich and resonant, singing a heartfelt solo into a microphone, every note echoing with emotion and passion, weaving a musical tapestry that touches the heart of every listener, drawing them into the story being told",
    "embodied as a gelatinous, dripping alien entity, its form ever-evolving, shimmering with an inner luminescence, invoking a sense of awe and caution, a marvel of extraterrestrial evolution",
    "displayed in a full-body frame, the slender silhouette of legs stretching to an impressive 80mm in length stands out, embodying grace and sophistication with every movement",
    "adorned in a unique blend of futuristic armor with the edgy aesthetics of cyberpunk, while radiant tattoos gleam softly from the skin, each inked design telling tales of valor, adventure, and distant worlds",
    "immersed in the soulful strings of an electric guitar, fingers plucking and sliding, crafting a mesmerizing solo that resonates with the fervor of the moment, while a captivated audience basks in the electrifying ambiance",
    "voice rich, powerful, and laden with emotion, singing a poignant solo into a sleek microphone, the lyrics touching deep chords within the hearts of an enraptured audience, each note weaving a narrative of love, loss, and hope",
    "taking the form of a gelatinous, otherworldly creature, its amorphous, dripping silhouette radiating an ethereal glow, invoking both intrigue and unease, a testament to the vast mysteries of the universe",
    "portrayed in a full-length view, with an emphasis on the sculpted elegance of legs, stretching an extraordinary 80mm, their poised stance a reflection of innate elegance and regality",
    "garbed in a harmonious fusion of sci-fi protective gear, the gritty undertones of a post-apocalyptic warrior, and the vibrant neon accents of cyberpunk fashion; the skin awash with luminescent tattoos, each symbol a beacon of stories untold",
    "engulfed in the rhythmic embrace of an electric guitar, fingers caressing and strumming, creating a solo that's both haunting and invigorating, the stage alive with pulsating lights and an audience lost in musical euphoria",
    "with a voice that's a blend of power and vulnerability, delivering a stirring solo into a microphone, the melodic journey touching on themes of dreams, heartbreak, and redemption, captivating listeners with its raw authenticity",
    "envisioned as a gelatinous, shape-shifting alien entity, its shimmering, dripping form a dance of lights and shadows, a mesmerizing yet unsettling spectacle of extraterrestrial beauty",
    "presented in a full-body perspective, the lithe grace of legs, extending a notable 80mm, becomes a focal point, their every motion exuding confidence and allure",
    "cloaked in an ensemble that melds the protective layers of futuristic armor, the raw essence of a battle-hardened warrior, and the neon-lit allure of cyberpunk aesthetics; radiant tattoos adorning the skin, each glow a testament to battles won and galaxies explored",
    "deep in the throes of an electrifying guitar solo, fingers nimbly navigating the strings, conjuring melodies that resonate with emotion, passion, and raw energy, creating an indelible bond with an entranced audience",
    "singing with a voice that oscillates between power and tenderness, pouring emotions into a heartfelt solo, each note and lyric weaving a tapestry of stories, dreams, and memories, leaving an indelible mark on every listener",
    "as a gelatinous, ever-evolving alien being, its form a mesmerizing play of light, texture, and motion, invoking a sense of wonder, curiosity, and the infinite possibilities of the cosmos",
]

PHOTOGRAPHY_STYLES = [
    "high fashion photography",
    "avant garde photography",
    "fashion photography",
    "portrait photography",
    "landscape photography",
    "documentary photography",
    "street photography",
    "action photography",
    "vintage photography",
]

DEVICE = [
    "Canon EOS 5D Mark IV with Canon EF 24-70mm f-2.8L II",
    "Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM",
    "Canon EOS M6 Mark II with Canon EF-M 32mm f-1.4",
    "Canon EOS R with Canon RF 28-70mm f-2L",
    "Canon EOS-1D X Mark III with Canon EF 50mm f-1.2L",
    "Canon PowerShot G5 X Mark II with Built-in 8.8-44mm f-1.8-2.8",
    "DJI Mavic Air 2 with Built-in 24mm f-2.8",
    "FujiFilm X-T4 with Fujinon XF 35mm f-2 R WR",
    "Fujifilm GFX 100 with GF 110mm f-2 R LM WR",
    "Fujifilm X-Pro3 with Fujinon XF 56mm f-1.2 R",
    "Fujifilm X-S10 with Fujinon XF 10-24mm f-4 R OIS WR",
    "Fujifilm X100V with Fujinon 23mm f-2",
    "GoPro HERO9 with Built-in f-2.8 Ultra-Wide",
    "Hasselblad 907X with Hasselblad XCD 30mm f-3.5",
    "Hasselblad X1D II with Hasselblad XCD 65mm f-2.8",
    "Kodak PIXPRO AZ901 with Built-in 4.3-258mm f-2.9-6.7",
    "Leica CL with Leica Summilux-TL 35mm f-1.4 ASPH",
    "Leica M10 with LEICA 35mm f-2 SUMMICRON-M ASPH",
    "Leica Q2 with Summilux 28mm f-1.7 ASPH",
    "Leica SL2 with Leica APO-Summicron-SL 50mm f-2 ASPH",
    "Nikon Coolpix P950 with Built-in 24-2000mm f-2.8-6.5",
    "Nikon D780 with Nikkor 14-24mm f-2.8G",
    "Nikon D850 with Nikkor 50mm f-1.8",
    "Nikon Z50 with Nikon Z DX 16-50mm f-3.5-6.3",
    "Nikon Z6 II with Nikon Z 24-70mm f-4 S",
    "Nikon Z7 with Nikon Z 70-200mm f-2.8 VR S",
    "Olympus OM-D E-M1 Mark III with M.Zuiko 12-40mm f-2.8",
    "Olympus OM-D E-M5 Mark III with M.Zuiko 40-150mm f-2.8",
    "Olympus PEN-F with M.Zuiko 17mm f-1.8",
    "Olympus Tough TG-6 with Built-in 4.5-18mm f-2-4.9",
    "Panasonic Lumix G9 with Leica DG 42.5mm f-1.2",
    "Panasonic Lumix GH5 with Leica DG 25mm f-1.4",
    "Panasonic Lumix S5 with Lumix S PRO 70-200mm f-2.8 O.I.S",
    "Panasonic S1R with Lumix S 50mm f-1.4",
    "Pentax 645Z with Pentax-D FA 645 55mm f-2.8",
    "Pentax K-1 Mark II with Pentax FA 43mm f-1.9 Limited",
    "Pentax KP with Pentax HD DA 20-40mm f-2.8-4",
    "Ricoh GR III with GR 18.3mm f-2.8",
    "Sigma fp with Sigma 45mm f-2.8 DG DN",
    "Sigma sd Quattro H with Sigma 24-70mm f-2.8 DG",
    "Sony A1 with Sony FE 20mm f-1.8 G",
    "Sony A6400 with Sony E 35mm f-1.8 OSS",
    "Sony A7C with Sony FE 28-60mm f-4-5.6",
    "Sony A7R IV with Sony FE 85mm f-1.4 GM",
    "Sony A9 II with Sony FE 24-70mm f-2.8 GM",
    "Sony RX100 VII with Built-in 24-200mm f-2.8-4.5",
]

# DEVICE = [
#     "Hasselblad X1D-50c",
#     "Nikon Z7II",
#     "Canon EOS R3",
#     "Sony A7R III",
#     "Alexa 65",
#     "Sony A7",
#     "Fujifilm XT3",
#     "Canon EOS R3",
#     "(35mm Hasselblad 500C/M camera using Lomography colour 400 film at f/1.8)",
# ]

PHOTOGRAPHER = [
    "Alessio Albi",
    "Alvin Langdon Coburn",
    "Anne Brigman",
    "Ansel Adams",
    "Anton Corbijn",
    "Berenice Abbott",
    "Bill Brandt",
    "Brooke DiDonato",
    "Bruce Davidson",
    "Bruno Barbey",
    "Chris Burkard",
    "Claude Cahun",
    "David Bailey",
    "David Burdeny",
    "Dawoud Bey",
    "Diane Arbus",
    "Dirk Braeckman",
    "Edward Burtynsky",
    "Edward S. Curtis",
    "Elina Brotherus",
    "Elsa Bleda",
    "Erwin Blumenfeld",
    "Flora Borsi",
    "Gregory Colbert",
    "Gregory Crewdson",
    "Guy Aroch",
    "Guy Bourdin",
    "Hans Bellmer",
    "Harry Benson",
    "Harry Callahan",
    "Henri Cartier-Bresson",
    "Ilse Bing",
    "Imogen Cunningham",
    "Iwan Baan",
    "James Balog",
    "Jamie Baldridge",
    "James Balog",
    "Julia Margaret Cameron",
    "Julie Blackmon",
    "Karl Blossfeldt",
    "Katia Chausheva",
    "Keith Carter",
    "Larry Burrows",
    "Larry Clark",
    "Laurent Baheux",
    "Lewis Baltz",
    "Lillian Bassman",
    "Lynsey Addario",
    "Margaret Bourke-White",
    "Marianne Breslauer",
    "Marta Bevacqua",
    "Mathew Brady",
    "Miki Asai",
    "Miles Aldridge",
    "Nick Brandt",
    "Nobuyoshi Araki",
    "Olive Cotton",
    "Patrick Demarchelier",
    "Paul Barson",
    "Petra Collins",
    "Petra Collins",
    "Richard Avedon",
    "Rineke Dijkstra",
    "Robby Cavanaugh",
    "Robert Adams",
    "Robert Capa",
    "Roger Ballen",
    "Ruth Bernhard",
    "Slim Aarons",
    "Tami Bone",
    "Tina Barney",
    "Vanley Burke",
]

ARTIST = [
    "Akihito Tsukushi",
    "Al Hirschfeld",
    "Alan Lee",
    "Albert Bierstadt",
    "Albert Uderzo",
    "Alberto Giacometti",
    "Alberto Vargas",
    "Albrecht Durer",
    "Alejandro Burdisio",
    "Aleksi Briclot",
    "Alessio Albi",
    "Alena Aenami",
    "Alex Gard",
    "Alex Grey",
    "Alex Maleev",
    "Alexander Jansson",
    "Alexander Milne Calder",
    "Alexandre Cabanel",
    "Alexei Savrasov",
    "Alexej von Jawlensky",
    "Alfred Kubin",
    "Alfredo Volpi",
    "Alice Neel",
    "Alice Rahon",
    "Alphonse Mucha",
    "Alyssa Monks",
    "Amanda Clark",
    "Amanda Sage",
    "Amedeo Modigliani",
    "Amelie Bernard",
    "Anders Zorn",
    "Andreas Achenbach",
    "Andrew Wyeth",
    "Andr\u00e9 Kert\u00e9sz",
    "Andr\u00e9 Masson",
    "Andy Fairhurst",
    "Andy Singer",
    "Andy Warhol",
    "Anita Malfatti",
    "Anna Dittmann",
    "Anne Geddes",
    "Anne Stokes",
    "Anne-Louis Girodet",
    "Annibale Carracci",
    "Annie Leibovitz",
    "Ansel Adams",
    "Anthony van Dyck",
    "Anton Fadeev",
    "Anton Otto",
    "Apollonia Saintclair",
    "Arkhip Kuindzhi",
    "Arnold B\u00f6cklin",
    "Arshile Gorky",
    "Art Spiegelman",
    "Artemisia Gentileschi",
    "Arthur Dove",
    "Asaf Hanuka",
    "Asher Brown Durand",
    "Ashley Wood",
    "Audrey Kawasaki",
    "Austin Briggs",
    "Balthus",
    "Banksy",
    "Barclay Shaw",
    "Barry Blitt",
    "Bastien Lecouffe Deharme",
    "Beatrix Potter",
    "Beauford Delaney",
    "Beeple",
    "Ben Shahn",
    "Benoit B. Mandelbrot",
    "Bernard Buffet",
    "Bernd and Hilla Becher",
    "Bernie Wrightson",
    "Berthe Morisot",
    "Bill Plympton",
    "Bjarke Ingels",
    "Bob Byerley",
    "Bob Eggleton",
    "Bob Ross",
    "Boris Vallejo",
    "Brandon Woelfel",
    "Brian Despain",
    "Brian Kesinger",
    "Brothers Hildebrandt",
    "Bruce Nauman",
    "Bruce Pennington",
    "Bruno Taut",
    "Camille Claudel",
    "Camille Corot",
    "Camille Pissarro",
    "Canaletto",
    "Candido Portinari",
    "Caravaggio",
    "Carl Holsoe",
    "Carl Larsson",
    "Carne Griffiths",
    "Caspar David Friedrich",
    "Chaim Soutine",
    "Charles Blackman",
    "Charles Demuth",
    "Charles E. Burchfield",
    "Charles Eames",
    "Charles Rennie Mackintosh",
    "Chesley Bonestell",
    "Chiharu Shiota",
    "Childe Hassam",
    "Chris Foss",
    "Chris Mars",
    "Chris Menges",
    "Chris Moore",
    "Christopher Doyle",
    "Cindy Sherman",
    "Clarence Holbrook Carter",
    "Claude Cahun",
    "Claude Lorrain",
    "Claude Monet",
    "Clive Barker",
    "Clive Madgwick",
    "Clovis Trouille",
    "Clyde Caldwell",
    "Coby Whitmore",
    "Codex Seraphinianus",
    "Coles Phillips",
    "Conrad Roset",
    "Craig Mullins",
    "Cuno Amiet",
    "Dale Chihuly",
    "Damien Hirst",
    "Dan Flavin",
    "Dan Mumford",
    "Daniel Gerhartz",
    "Daniel Merriam",
    "Daniel Ridgway Knight",
    "Dave Gibbons",
    "Dave McKean",
    "David Alfaro Siqueiros",
    "David B. Mattingly",
    "David Burliuk",
    "David Hockney",
    "David Park",
    "Dean Ellis",
    "Dennis Stock",
    "Di Cavalcanti",
    "Diane Arbus",
    "Diego Velazquez",
    "Dion Beebe",
    "Don Bluth",
    "Don Maitz",
    "Donato Giancola",
    "Dora Maar",
    "Dorothea Lange",
    "Dorothea Tanning",
    "Dorothy Lathrop",
    "Doug Chiang",
    "Dustin Nguyen",
    "E.H. Shepard",
    "Earl Norem",
    "Ed Binkley",
    "Ed Emshwiller",
    "Ed Mell",
    "Edgar Degas",
    "Edmund Leighton",
    "\u00c9douard Manet",
    "Edvard Munch",
    "Edward Weston",
    "Edwin Austen Abbey",
    "Edward Hopper",
    "Egon Schiele",
    "Eikoh Hosoe",
    "El Greco",
    "Elaine de Kooning",
    "Ellen Jewett",
    "Elliott Erwitt",
    "Elsa Beskow",
    "Emil Melmoth",
    "Emil Nolde",
    "Emily Carr",
    "Emmanuel Lubezki",
    "Enki Bilal",
    "Eric Gill",
    "Eric Lacombe",
    "Erich Heckel",
    "Erich Ludwig Kirchner",
    "Ernst Fuchs",
    "Ernst Haeckel",
    "Esao Andrews",
    "Eug\u00e8ne Delacroix",
    "Eva Hesse",
    "Evelyn De Morgan",
    "Eyvind Earle",
    "Fairfield Porter",
    "Farel Dalrymple",
    "Fernand L\u00e9ger",
    "Fernando Botero",
    "Filippo Lippi",
    "Francis Bacon",
    "Francis Picabia",
    "Francisco Goya",
    "Frank Auerbach",
    "Frank Frazetta",
    "Frank Lloyd Wright",
    "Frank Miller",
    "Frank Schoonover",
    "Franklin Booth",
    "Franz Kline",
    "Franz Marc",
    "Franz Sedlacek",
    "Franz Xaver Winterhalter",
    "Fred Tomaselli",
    "Frederick Lord Leighton",
    "Frida Kahlo",
    "Friedensreich Regentag Dunkelbunt Hundertwasser",
    "Frits Van den Berghe",
    "F\u00e9lix Vallotton",
    "Gabriel Pacheco",
    "Garry Trudeau",
    "Gary Larson",
    "Gaston Bussiere",
    "Gediminas Pranckevicius",
    "Geof Darrow",
    "George Cruikshank",
    "George Frederic Watts",
    "George Grosz",
    "George Inness",
    "George Luks",
    "Georges Rouault",
    "Georges Seurat",
    "Georgia O'Keeffe",
    "Gerald Brom",
    "Gerhard Munthe",
    "Gerhard Richter",
    "Gertrude Abercrombie",
    "Giacomo Balla",
    "Giorgio de Chirico",
    "Giuseppe Arcimboldo",
    "Glenn Fabry",
    "Go Nagai",
    "Gottfried Helnwein",
    "Graciela Iturbide",
    "Grandma Moses",
    "Greg Hildebrandt",
    "Greg Rutkowski",
    "Gregory Crewdson",
    "Grzegorz Domaradzki",
    "Guido Borelli da Caluso",
    "Guillermo del Toro",
    "Gustav Klimt",
    "Gustav Vigeland",
    "Gustave Caillebotte",
    "Gustave Courbet",
    "Gustave Dore",
    "Gustave Moreau",
    "H. R. Giger",
    "Hal Foster",
    "Hannah H\u00f6ch",
    "Hans Baldung",
    "Hans Bellmer",
    "Harold Elliott",
    "Harriet Backer",
    "Harry Clarke",
    "Harry Gruyaert",
    "Heinrich Kley",
    "Hendrik Kerstens",
    "Henri Harpignies",
    "Henri Matisse",
    "Henri Rousseau",
    "Henri de Toulouse-Lautrec",
    "Henri-Edmond Cross",
    "Henry Fuseli",
    "Henry Ossawa Tanner",
    "Herg\u00e9",
    "Hieronymus Bosch",
    "Hilma af Klint",
    "Hirohiko Araki",
    "Hiromu Arakawa",
    "Hiroshi Nagai",
    "Hiroshi Yoshida",
    "Hokusai",
    "Honor\u00e9 Daumier",
    "Hope Gangloff",
    "Howard Finster",
    "Howard Hodgkin",
    "Hubert Robert",
    "Hugh Ferriss",
    "Hugh Kretschmer",
    "Hundertwasser",
    "Ian McQue",
    "Ian Miller",
    "Igor Morski",
    "Ilkka Uimonen",
    "Ilya Repin",
    "Irma Stern",
    "Isaac Levitan",
    "Isamu Noguchi",
    "Ivan Aivazovsky",
    "Ivan Albright",
    "Ivan Bilibin",
    "Ivan Generalic",
    "Ivan Shishkin",
    "J. J. Grandville",
    "J.C. Leyendecker",
    "J.M.W. Turner",
    "Jacek Yerka",
    "Jack Butler Yeats",
    "Jack Davis",
    "Jack Gaughan",
    "Jack Kirby",
    "Jackson Pollock",
    "Jacob Lawrence",
    "Jacob Riis",
    "Jacques-Laurent Agasse",
    "Jakub Rozalski",
    "James Abbott McNeill Whistler",
    "James C. Christensen",
    "James Ensor",
    "James Jean",
    "James Turrell",
    "Jamie Hewlett",
    "Jan van Goyen",
    "Jaroslaw Jasnikowski",
    "Jasmine Becket-Griffith",
    "Jason Edmiston",
    "Jason Limon",
    "Jean Arp",
    "Jean Delville",
    "Jean Giraud (Moebius)",
    "Jean Leon Gerome",
    "Jean Metzinger",
    "Jean-Auguste-Dominique Ingres",
    "Jean-Baptiste Carpeaux",
    "Jean-Baptiste-Sim\u00e9on Chardin",
    "Jean-Honore Fragonard",
    "Jean-Michel Basquiat",
    "Jean-Pierre Vasarely (Yvaral)",
    "Jeff Easley",
    "Jeff Koons",
    "Jeff Lemire",
    "Jeffrey Catherine Jones",
    "Jeffrey Smith",
    "Jeffrey T. Larson",
    "Jeremy Geddes",
    "Jeremy Lipking",
    "Jeremy Mann",
    "Jesper Ejsing",
    "Jim Burns",
    "Jim Fitzpatrick",
    "Jim Lee",
    "Jim Steranko",
    "Jithesh",
    "Joan Mir\u00f3",
    "Joaquin Sorolla",
    "Johan Christian Dahl",
    "Johannes Vermeer",
    "Johfra Bosschart",
    "John Atkinson Grimshaw",
    "John Bauer",
    "John Berkey",
    "John Blanche",
    "John Carpenter",
    "John Constable",
    "John Duncan",
    "John Frederick Kensett",
    "John Harris",
    "John Hoyland",
    "John James Audubon",
    "John Kenn Mortensen",
    "John Kricfalusi",
    "John Martin",
    "John Perceval",
    "John Philip Falter",
    "John Romita Jr",
    "John Singer Sargent",
    "John Stephens",
    "John William Waterhouse",
    "Jonas Bendiksen",
    "Josan Gonzalez",
    "Joseph Cornell",
    "Joseph Ducreux",
    "Joseph Stella",
    "Josephine Wall",
    "Jules Bastien-Lepage",
    "Jules Feiffer",
    "Jules Pascin",
    "Junji Ito",
    "Justin Gerard",
    "Kaethe Butcher",
    "Kaja Foglio",
    "Karel Thole",
    "Karl Blossfeldt",
    "Karl Schmidt-Rottluff",
    "Karol Bak",
    "Kate Greenaway",
    "Kathe Kollwitz",
    "Katsuhiro Otomo",
    "Katsushika Hokusai",
    "Kay Nielsen",
    "Kay Sage",
    "Kazimir Malevich",
    "Kehinde Wiley",
    "Kelly Freas",
    "Kelly McKernan",
    "Ken Sugimori",
    "Kenojuak Ashevak",
    "Kent Monkman",
    "Kentaro Miura",
    "Kilian Eng",
    "Kim Jung Gi",
    "Kuang Hong",
    "Larry Elmore",
    "Lasar Segall",
    "Laurel Burch",
    "Laurie Greasley",
    "Laurie Lipton",
    "Lawren Harris",
    "Le caravaggesque",
    "Lee Krasner",
    "Lee Madgwick",
    "Leiji Matsumoto",
    "Leon Bankst",
    "Leonardo da Vinci",
    "Leonid Afremov",
    "Liam Wong",
    "Liniers",
    "Lisa Frank",
    "Louis Comfort Tiffany",
    "Louis Wain",
    "Lovis Corinth",
    "Luc Schuiten",
    "Lucian Freud",
    "Luis Royo",
    "Lyonel Feininger",
    "Lyubov Popova",
    "M.C. Escher",
    "M.W. Kaluta",
    "Mab Graves",
    "Makoto Shinkai",
    "Malcolm Liepke",
    "Man Ray",
    "Marc Chagall",
    "Mark Lague",
    "Marc Simonetti",
    "Marco Mazzoni",
    "Marek Okon",
    "Margaret Boden",
    "Margaret Bruce Wells",
    "Margaret Brundage",
    "Margaret Garland",
    "Margaret Geddes",
    "Margaret Graeme Niven",
    "Margaret Keane",
    "Margaret Macdonald Mackintosh",
    "Maria Prymachenko",
    "Maria Sibylla Merian",
    "Marianne von Werefkin",
    "Mario Testino",
    "Marjorie Strider",
    "Mark Brooks",
    "Mark Catesby",
    "Mark Rothko",
    "Mark Ryden",
    "Marsden Hartley",
    "Martin Parr",
    "Martin Johnson Heade",
    "Martiros Saryan",
    "Mary Blair",
    "Mary Cassatt",
    "Masamune Shirow",
    "Masashi Kishimoto",
    "Mat Collishaw",
    "Mati Klarwein",
    "Matt Groening",
    "Matthias Grunewald",
    "Matti Suuronen",
    "Maurice Sendak",
    "Max Beckmann",
    "Max Ernst",
    "Max Pechstein",
    "Max Weber",
    "Maxfield Parrish",
    "Meret Oppenheim",
    "Michael Deforge",
    "Michael Whelan",
    "Michelangelo",
    "Mike Mignola",
    "Mikhail Vrubel",
    "Miles Aldridge",
    "Milton Avery",
    "Milton Glaser",
    "Moebius (Jean Giraud)",
    "Mort Drucker",
    "Nan Goldin",
    "Nao Emoto",
    "Naoto Hattori",
    "Natalia Goncharova",
    "Neil Welliver",
    "Nele Zirnite",
    "Nell Dorr",
    "Nicholas Roerich",
    "Nick Knight",
    "Nikos Economopoulos",
    "Nobuyoshi Araki",
    "Noriyoshi Ohrai",
    "Norman Rockwell",
    "Nychos",
    "Odd Nerdrum",
    "Odilon Redon",
    "Oliver Jeffers",
    "Oskar Kokoschka",
    "Oskar Schlemmer",
    "Otto Dix",
    "Otto Marseus van Schrieck",
    "Pablo Picasso",
    "Pascal Campion",
    "Patrick Henry Bruce",
    "Patrick Heron",
    "Patrick Nagel",
    "Patrick Woodroffe",
    "Paul Cezanne",
    "Paul Delvaux",
    "Paul Gauguin",
    "Paul Gustav Fischer",
    "Paul Klee",
    "Paul Rand",
    "Paula Modersohn-Becker",
    "Pendleton Ward",
    "Peter Bagge",
    "Peter Elson",
    "Peter Gric",
    "Peter Kemp",
    "Peter Max",
    "Peter Paul Rubens",
    "Phil Foglio",
    "Philip Guston",
    "Philip Pearlstein",
    "Philip-Lorca diCorcia",
    "Pierre Bonnard",
    "Pierre-Auguste Renoir",
    "Piet Mondrian",
    "Pieter Claesz",
    "Platon",
    "Quentin Blake",
    "Rachel Ignotofsky",
    "Rafal Olbinski",
    "Ralph McQuarrie",
    "Ralph Steadman",
    "Ram\u00f3n Casas",
    "Randolph Caldecott",
    "Raphael Lacoste",
    "Raphaelite",
    "Ray Caesar",
    "Ray Earnes",
    "Raymond Briggs",
    "Raymond Swanland",
    "Rebeca Saray",
    "Rebecca Guay",
    "Reginald Marsh",
    "Remedios Varo",
    "Ren\u00e9 Magritte",
    "Richard Corben",
    "Richard Dadd",
    "Richard Diebenkorn",
    "Richard Doyle",
    "Richard Scarry",
    "Ridley Scott",
    "Rineke Dijkstra",
    "Rob Gonsalves",
    "Rob Liefeld",
    "Robert Bechtle",
    "Robert Capa",
    "Robert Crumb",
    "Robert Delaunay",
    "Robert McCall",
    "Robert McGinnis",
    "Robert Motherwell",
    "Robert Rauschenberg",
    "Robert Williams",
    "Roberto Ferri",
    "Roberto Matta",
    "Rockwell Kent",
    "Rodney Matthews",
    "Rodrigo Prieto",
    "Roger Dean",
    "Romare Bearden",
    "Romero Britto",
    "Ron Walotsky",
    "Rosa Bonheur",
    "Roy Lichtenstein",
    "Rudolf Hausner",
    "Rufino Tamayo",
    "Russ Mills",
    "Ruth Bernhard",
    "Ryan Hewett",
    "Ryo Takemasa",
    "Ryohei Hase",
    "Sally Mann",
    "Salvador Dali",
    "Sam Bosma",
    "Sam Francis",
    "Sam Guay",
    "Sam Toft",
    "Santiago Caruso",
    "Satoshi Kon",
    "Sebastian Kr\u00fcger",
    "Sebasti\u00e3o Salgado",
    "Sergio Toppi",
    "Shaun Tan",
    "Shepard Fairey",
    "Shiki",
    "Shinji Aramaki",
    "Shotaro Ishinomori",
    "Sidney Nolan",
    "Sidney Prior Hall",
    "Simon Bisley",
    "Simon St\u00e5lenhag",
    "Simone Martini",
    "Sir James Guthrie",
    "Sir Max Beerbohm",
    "Sonia Delaunay",
    "Stanley Donwood",
    "Stefan Gesell",
    "Stephanie Law",
    "Stephen Gammell",
    "Steve Argyle",
    "Steve Dillon",
    "Steve Ditko",
    "Steve McCurry",
    "Storm Thorgerson",
    "Stuart Davis",
    "Syd Mead",
    "Sylvain Chomet",
    "Taiyo Matsumoto",
    "Takashi Murakami",
    "Takato Yamamoto",
    "Takehiko Inoue",
    "Taro Okamoto",
    "Tarsila do Amaral",
    "Tatsuro Kiuchi",
    "Ted Nasmith",
    "Terry Oakes",
    "Tex Avery",
    "Theodor Seuss Geisel",
    "Thomas Cole",
    "Thomas Gainsborough",
    "Thomas Kinkade",
    "Tibor Nagy",
    "Tillie Walden",
    "Tim Burton",
    "Tim Doyle",
    "Tim Hildebrandt",
    "Tim White",
    "Tivadar Csontvary Kosztka",
    "Todd McFarlane",
    "Tom Bagshaw",
    "Tom Lovell",
    "Tom Thomson",
    "Tom Whalen",
    "Tomasz Alen Kopera",
    "Tomasz Jedruszek",
    "Tomek Setowski",
    "Tomer Hanuka",
    "Tomi Ungerer",
    "Tomioka Tessai",
    "Tommaso Dolabella",
    "Tommaso Masaccio",
    "Tommaso Redi",
    "Tomokazu Matsuyama",
    "Tom\u00e0s Barcel\u00f3",
    "Tony DiTerlizzi",
    "Tove Jansson",
    "Tsutomu Nihei",
    "Ub Iwerks",
    "Van Herpen",
    "Victo Ngai",
    "Victor Brauner",
    "Victor Moscoso",
    "Victor Ngai",
    "Victor Vasarely",
    "Viktor Vasnetsov",
    "Vilhelm Hammershoi",
    "Vilmos Zsigmond",
    "Vincent van Gogh",
    "Virgil Finlay",
    "Walter Crane",
    "Walt Disney",
    "Wassily Kandinsky",
    "Wayne Barlowe",
    "Weegee",
    "Wes Anderson",
    "Will Simpson",
    "Wifredo Lam",
    "William Blake",
    "William Gropper",
    "William Henry Hunt",
    "William Hogarth",
    "William Morris",
    "William S Burroughs",
    "William Stout",
    "William-Adolphe Bouguereau",
    "Winslow Homer",
    "Wong Kar-Wai",
    "Yaacov Agam",
    "Yayoi Kusama",
    "Yoshitaka Amano",
    "Yousuf Karsh",
    "Yuumei",
    "Yves Klein",
    "Yves Tanguy",
    "Zack Snyder",
    "Zaha Hadid",
    "Zdzislaw Beksinski",
]

DIGITAL_ARTFORM = [
    "Glitch Art art",
    "Digital Painting art",
    "Acrylic Paint art",
    "Algorithmic art",
    "Animation art",
    "Art glass art",
    "Assemblage art",
    "Augmented reality art",
    "Batik art",
    "Beadwork art",
    "Body painting art",
    "Bookbinding art",
    "Cast paper art",
    "Ceramics art",
    "Bronze art",
    "Charcoal art",
    "Collage art",
    "Collagraphy art",
    "Colored pencil art",
    "Computer-generated imagery (cgi) art",
    "Crochet art",
    "Decoupage art",
    "Digital sculpture art",
    "Foam carving art",
    "Found objects art",
    "Fresco art",
    "Glass art",
    "Gouache art",
    "Graffiti art",
    "Ice art",
    "Ink wash painting art",
    "Installation art",
    "Interactive media art",
    "Lenticular printing art",
    "Light projection art",
    "Lithography art",
    "Marble art",
    "Metal art",
    "Metalpoint art",
    "Miniature painting art",
    "Mixed media art",
    "Monotype printing art",
    "Neon art",
    "Oil painting art",
    "Origami art",
    "Papier-mache art",
    "Pastel art",
    "Pen and ink art",
    "Plastic arts",
    "Polymer clay art",
    "Printmaking art",
    "Puppetry art",
    "Pyrography art",
    "Quilling art",
    "Quilting art",
    "Recycled art",
    "Resin art",
    "Sand art",
    "Sound art",
    "Silverpoint art",
    "Spray paint art",
    "Stone art",
    "Tempera art",
    "Tattoo art",
    "Video art",
    "Watercolor art",
    "Wax art",
    "Wood art",
]

PLACE = [
    "indoor",
    "outdoor",
    "at night",
    "in the park",
    "studio",
    "at a party",
    "at a festival",
    "at a concert",
    "on persons home planet",
    "magical portal with particles",
    "in a neon lit city",
    "in a cyberpunk city",
    "in a fantasy world",
    "glamour photography",
    "fashion photography",
    "at home",
    "at work",
    "at a cafe",
    "at a gym",
    "at a hotel",
    "at a concert performance",
    "at the beach",
    "at a museum",
    "in a hidden city deep in the rainforest",
    "in a floating island in the sky",
    "in an underground world beneath the earths surface ",
    "in a secret garden hidden in a mysterious maze",
    "in a grand castle on the top of a remote mountain",
    "in a enchanted forest with talking animals and magical creatures",
    "in a mystical island filled with ancient ruins and hidden treasure",
    "in a faraway planet with a unique and alien landscape",
    "in a hidden paradise hidden behind a waterfall",
    "in a dreamlike world where anything is possible and the impossible is real",
    "in a hidden oasis in the desert",
    "in a secret underground city",
    "in an underwater kingdom",
    "in a lost temple in the jungle",
    "in a castle in the clouds",
    "in a hidden valley in the mountains",
    "in a uturistic city on a distant planet",
    "in a mystical land of eternal twilight",
    "Smoke and ash in the air",
    "suburban america",
    "suburbs",
    "slums",
    "at the sea",
    "at the ocean",
    "at the lake",
    "at the river",
    "at the waterfall",
    "in the labyrinth",
    "in a lab"
    "rendered in a 2.5D isometric perspective. Soft gradients add dimension, pastel color scheme",
]
LIGHTING = [
    "popping colors, popart style",
    "bokeh",
    "dramatic",
    "golden hour",
    "depth of field",
    "movie still",
    "colorful",
    "soft lighting",
    "studio lighting with strong rim light",
    "ambient lighting",
    "sun rays",
    "cinematic lighting",
    "characteristics of the light",
    "volumetric lighting",
    "natural point rose",
    "outdoor lighting",
    "soft pastel lighting colors scheme",
    "sensual lighting",
    "neon lights",
    "baroque",
    "rokoko",
    "rim light, iridescent accents",
    "neoclassicism",
    "realism",
    "fantastic colors",
    "surrealism",
    "futurism",
    "accent lighting",
    "high key lighting",
    "low key lighting",
    "strong backlight",
    "artificial lighting",
    "decorative lighting",
    "recessed lighting",
    "wall sconces lighting",
    "laser lighting",
    "multi-colored lighting",
    "mood lighting",
    "accent lighting",
    "projection lighting",
    "bioluminiscent",
    "plasma",
    "ice",
    "water",
    "rule of thirds",
    "anamorphic lens flare",
    "sharp focus",
    "vivid colors",
    "masterpiece",
    "colors",
    "8k",
    "atmospheric",
    "cinematic sensual",
    "hyperrealistic",
    "big depth of field",
    "glow effect",
    "modelshoot style",
    "shallow depth of field",
    "hdr",
    "dynamic composition",
    "broad light",
    "natural lighting",
    "elegant pose",
    "flowing",
    "film photo",
    "extremely detailed",
    "big depth of field",
    "matte skin, pores, wrinkles",
    "hyperdetailed",
    "(abstract:1.3)",
    "intricate and low contrast detailed",
    "(composition)",
    "film grain",
    "(8k, RAW photo, best quality, masterpiece:1.2)",
    "(realistic, photo-realistic:1.37)",
    "beautiful detailed eyes, beautiful detailed lips, a captivating gaze, and an alluring expression",
    "beautiful dynamic dramatic dark moody lighting",
    "(detailed face:1.3)",
    "multilayered realism",
    "majestically strides forward toward us with abandon",
    "disintegrating moon",
    "extremely intricate details",
    "anatomical beauty",
    "high fantasy",
    "detailed skin pores",
    "flat color scheme",
    "80s music clip background",
    "Use a backlighting effect to add depth to the image. impressionistic painting style, john singer sarget, blue pallette",
    "(natural skin texture, hyperrealism, soft light, sharp:1.2)",
    "(cinematic, teal and orange:0.85)",
    "(intricate skin detail:1.3), (wrinkles:1.2),(skin blemishes:1.1),(skin pores:1.1),(detailed face:1.3), (lips slightly parted:1.0)",
    "(muted colors, dim colors, soothing tones:1.3), low saturation, (hyperdetailed:1.2)",
    "(noir:0.4), (intricate details:1.12), hdr, (intricate details, hyperdetailed:1.15)",
    "(neutral colors:1.2), art, (hdr:1.5), (muted colors:1.1), (pastel:0.2), hyperdetailed",
    "dramatic lighting",
    "((landscape view)), 4k unity, (best illumination)",
    "dynamic angle",
    "detailed freckles skin",
    "movie grain",
    "epic composition",
    "Tarot Card style",
    "(solo focus, one frame)",
    "(masterpiece, best quality, ultra-detailed, highres)",
    "biopunk",
    "dramatic Pull from the ghost of a virtual memory",
    "gritty industrial",
    "(soothing tones, insane details, intricate details, hyperdetailed,photorealistic,dim subdued lighting)",
    "popping colors evoking a vibrant and energetic mood, reminiscent of pop art masterpieces from the mid-20th century, where bold contrasts and exaggerated forms reign supreme",
    "bokeh lighting that creates a dreamy, blurred background filled with small, out-of-focus light points, emphasizing the subject and adding depth and dimension to the photograph",
    "dramatic lighting, casting deep shadows and highlighting only specific parts of the subject, creating an intense and moody atmosphere, perfect for conveying emotion and tension",
    "golden hour lighting, where the soft, warm glow of the sun as it's just above the horizon casts a magical and ethereal light, making everything it touches seem to glow from within",
    "depth of field emphasizing the subject by blurring out the background, creating a clear focal point and adding a three-dimensional feel to the image",
    "movie still lighting, replicating the look and feel of a cinematic moment frozen in time, with balanced contrasts and tones that evoke emotion and narrative",
    "colorful lighting, awash with a spectrum of vibrant hues, each shade carefully chosen to complement and contrast, creating a visually captivating scene",
    "soft lighting, bathing the subject in a gentle, diffused glow that reduces harsh shadows and offers a calming, serene atmosphere",
    "studio lighting with strong rim light, emphasizing the subject's contours and creating a halo effect, separating them from the background and adding depth",
    "ambient lighting, providing a natural, even illumination throughout the scene, capturing the essence of the environment and setting the mood",
    "sun rays piercing through, casting long, dramatic beams of light that highlight particles in the air, creating a heavenly and ethereal ambiance",
    "cinematic lighting, characterized by dramatic contrasts, sharp highlights, and deep shadows, reminiscent of scenes from blockbuster films, evoking tension and emotion",
    "characteristics of the light, focusing on the source, intensity, and direction, each element playing a crucial role in shaping the mood and narrative of the image",
    "volumetric lighting, creating beams or columns of light that appear to shine through a medium, such as fog or dust, adding depth and a three-dimensional quality",
    "natural point rose lighting, offering a delicate, soft illumination reminiscent of the gentle hues seen during a rose-tinted sunrise or sunset",
    "outdoor lighting, harnessing the natural brilliance of the sun or the subtle glow of the moon, capturing the essence of the environment, from sunlit meadows to moonlit beaches",
    "soft pastel lighting colors scheme, enveloping the scene in a dreamy, whimsical hue reminiscent of a delicate watercolor painting, evoking feelings of nostalgia and serenity",
    "sensual lighting, with a warm, intimate glow that accentuates curves and contours, creating an atmosphere of allure and romance",
    "neon lights casting vibrant, electric glows in blues, pinks, and purples, reminiscent of urban nightlife and futuristic cityscapes",
    "baroque lighting, characterized by dramatic contrasts and intricate shadow patterns, reminiscent of the grandeur and opulence of the Baroque art movement",
    "rokoko lighting, with its soft, playful illumination, evoking the light-hearted and ornate aesthetics of the Rococo era",
    "rim light with iridescent accents, creating a shimmering halo around the subject, adding depth and a touch of fantasy to the scene",
    "neoclassicism lighting, reflecting the clean, symmetrical, and harmonious aesthetics of the Neoclassical art movement, with a focus on order and balance",
    "realism lighting, capturing the scene in its most natural and unaltered state, emphasizing authenticity and true-to-life representation",
    "fantastic colors, blending reality with imagination, using a palette that's both vibrant and otherworldly, painting scenes straight out of dreams and fairy tales",
    "surrealism lighting, blending dream and reality, creating scenes that challenge perceptions and evoke wonder, with unexpected contrasts and ethereal glows",
    "futurism lighting, highlighting technology and motion, using dynamic angles and sharp, electric hues, reminiscent of a fast-paced, technologically advanced future",
    "accent lighting, focusing on specific points or objects, drawing attention and adding depth to the scene by highlighting certain areas while leaving others in shadow",
    "high key lighting, utilizing bright lights and minimal shadows to create an uplifting, airy atmosphere with an emphasis on clarity and optimism",
    "low key lighting, characterized by deep shadows and stark contrasts, creating a mood of mystery, drama, and tension",
    "strong backlight, illuminating the subject from behind, creating silhouettes and emphasizing outlines, adding drama and depth",
    "artificial lighting, using man-made sources like bulbs or LEDs to illuminate the scene, offering controlled and consistent illumination",
    "decorative lighting, designed to be aesthetically pleasing, adding visual interest and ambiance to a space beyond mere illumination",
    "recessed lighting, embedded into ceilings or walls, providing a clean, streamlined look while casting a gentle, diffused glow",
    "wall sconces lighting, mounted fixtures that cast light upward or downward, adding elegance and warmth to a room while highlighting architectural details",
    "laser lighting, emitting concentrated beams of light, often used in entertainment settings for dynamic, high-energy effects",
    "multi-colored lighting, utilizing a spectrum of hues to create vibrant, playful, and mood-enhancing scenes, evoking different emotions and atmospheres",
    "mood lighting, adjusted to fit the ambiance and emotions of the scene, shifting between warm and cool tones to evoke specific feelings and atmospheres",
    "projection lighting, using projectors to cast images or patterns onto surfaces, creating dynamic visuals and transforming the environment",
    "bioluminescent lighting, emanating from living organisms like deep-sea creatures, casting a mesmerizing, ethereal glow in the surrounding darkness",
    "plasma lighting, characterized by bright, electric hues and dynamic patterns reminiscent of plasma balls or northern lights",
    "ice lighting, using the refractive properties of ice to create a cool, shimmering illumination, reminiscent of icy landscapes and winter wonderlands",
    "water lighting, reflecting and refracting light through water surfaces, creating rippling, fluid patterns and a serene ambiance",
    "rule of thirds lighting, strategically placing key elements at the intersections of imaginary grid lines, creating a balanced and harmonious composition",
    "anamorphic lens flare, producing elongated, horizontal flares and adding a cinematic, dreamy touch to scenes",
    "sharp focus lighting, ensuring that the subject is in clear, crisp focus, with every detail highlighted and visible, contrasting with a blurred background",
    "vivid colors lighting, using bold and saturated hues to create a lively, energetic atmosphere, making the scene pop with intensity",
    "masterpiece lighting, crafted with meticulous attention to detail and precision, creating a work of art that stands out as exceptional and timeless",
    "colors lighting, emphasizing the play of different hues, shadows, and highlights, creating a rich tapestry of visual elements",
    "8k lighting, capturing scenes in ultra-high resolution, ensuring every minute detail is illuminated and presented with unparalleled clarity and precision",
    "atmospheric lighting, creating a mood by using a blend of natural and artificial sources, often coupled with environmental elements like fog or mist, to evoke emotion",
    "cinematic sensual lighting, combining the dramatic flair of movie scenes with soft, seductive hues, evoking passion and intensity",
    "hyperrealistic lighting, replicating real-world lighting conditions with meticulous detail, ensuring every nuance of light and shadow is accurately portrayed",
    "big depth of field lighting, illuminating both the foreground and background with equal clarity, providing a comprehensive view of the entire scene",
    "glow effect, adding a soft radiance around light sources or subjects, creating a dreamy, ethereal ambiance",
    "modelshoot style lighting, tailored for fashion photography, emphasizing the model's features and attire, often with a balance of hard and soft lights",
    "shallow depth of field lighting, focusing on a specific subject while allowing the background to blur, drawing attention to the focal point",
    "hdr lighting, using High Dynamic Range to capture a wider spectrum of lights and darks, creating images with intense contrasts and vivid details",
    "dynamic composition lighting, arranging light sources in a way that leads the viewer's eye through the scene, creating movement and interest",
    "broad light, illuminating the subject from a wider angle, reducing shadows and providing a more even distribution of light",
    "natural lighting, relying on the sun or moon, capturing the raw, unaltered beauty of a scene, from the golden tones of sunrise to the cool hues of twilight",
]

# class CommaSeparatedList:
#     RETURN_TYPES = ("STRING",)
#     FUNCTION = "generate_string"
#     CATEGORY = "PromptGenerator"

#     @classmethod
#     def IS_CHANGED(cls):
#         return float("NaN")

#     @classmethod
#     def INPUT_TYPES(cls):
#         return {
#             "required": {
#                 "csl": ("STRING", {}),
# 			},
# 		}

#     def generate_string(
#         self,
# 		csl,
# 	):
#         print(csl)
#         return tuple(csl.split(","))
# class CSVPromptGenerator:
#     RETURN_TYPES = ("STRING",)
#     FUNCTION = "generate_prompt"
#     CATEGORY = "PromptGenerator"

#     @classmethod
#     def IS_CHANGED(cls):
#         return float("NaN")

#     @classmethod
#     def INPUT_TYPES(cls):
#         return {
#             "required": {
#                 "subject": ("STRING", {}),
#                 "artform": (
#                     ARTFORM,
#                     {"default": "random"},
#                 ),
#                 "photo_type": ("STRING", {}),
#                 "default_tags": ("STRING", {}),
#                 "roles": ("STRING", {}),
#                 "hairstyles": ("STRING", {}),
#                 "additional_details": ("STRING", {}),
#                 "photography_styles": ("STRING", {}),
#                 "device": ("STRING", {}),
#                 "photographer": ("STRING", {}),
#                 "artist": ("STRING", {}),
#                 "digital_artform": ("STRING", {}),
#                 "place": ("STRING", {}),
#                 "lighting": ("STRING", {}),
#             },
#         }
#     def split_and_choose(self, input_str):
#         choices = [choice.strip() for choice in input_str.split(',')]
#         return random.choice(choices)

#     def get_choice(self, input_str, default_choices):
#         if input_str.lower() == 'disabled':
#             return ""
#         elif ',' in input_str:
#             return self.split_and_choose(input_str)
#         elif input_str.lower() == 'random':
#             return random.choice(default_choices)
#         else:
#             return input_str

#     def generate_prompt(self, **kwargs):
#         components = []
#         is_photographer = kwargs.get("artform", "").lower() == "photography" or (
#             kwargs.get("artform", "").lower() == "random" and random.choice([True, False])
#         )

#         if is_photographer:
#             photo_type_choice = self.get_choice(kwargs.get('photo_type', ''), kwargs.get('photo_type', ''))
#             if photo_type_choice:
#                 components.append(f"{photo_type_choice} of ")
#     # if photo_type_choice is empty, nothing gets appended
#         else:
#             digital_artform_choice = self.get_choice(kwargs.get('digital_artform', ''), kwargs.get('digital_artform', ''))
#             if digital_artform_choice:  # Checks if digital_artform_choice has a value
#                 components.append(f"{digital_artform_choice} of ")
#     # if digital_artform_choice is empty, nothing gets appended

#         lighting = kwargs.get('lighting', "").lower()
#         components.append(lighting)

#         params = [
#             ('subject', 'default_tags', kwargs.get('subject', '')),
#             ('roles', kwargs.get('roles', '')),
#             ('hairstyles', kwargs.get('hairstyles', '')),
#             ('additional_details', kwargs.get('additional_details', '')),
#             ('place', kwargs.get('place', ''))
#         ]
#         components.extend([self.get_choice(kwargs.get(param[0], ''), param[1]) for param in params])

#         if is_photographer:
#             params = [
#                 ('photography_styles', kwargs.get('photography_styles', '')),
#                 ('device', kwargs.get('device', '')),
#                 ('photographer', kwargs.get('photographer', ''))
#             ]
#             components.extend([
#                 self.get_choice(kwargs.get(param[0], ''), param[1]) for param in params
#             ])
#             components[-2] = f"shot on {components[-2]}"
#             components[-1] = f"photo by {components[-1]}"
#         else:
#             if kwargs.get('artists', ''):
#                 artist_choice = self.get_choice(kwargs.get('artist', ''), kwargs.get('artists', ''))
#                 if artist_choice:  # Checks if artist_choice has a value
#                     components.append(f"by {artist_choice}")

#         prompt = " ".join(components)
#         prompt = re.sub(' +', ' ', prompt)
#         print(f"AUTOPROMPT: {prompt}")
#         return (prompt,)


class PromptGenerator:
    RETURN_TYPES = (
        "STRING",
        "INT",
    )
    RETURN_NAMES = (
        "prompt",
        "seed",
    )
    FUNCTION = "generate_prompt"
    CATEGORY = "PromptGenerator"

    def __init__(self, seed=None):
        self.rng = random.Random(seed)

    @classmethod
    def IS_CHANGED(cls):
        return float("NaN")

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "seed": (
                    "INT",
                    {"default": 0, "min": 0, "max": 1125899906842624},
                ),
                "subject": ("STRING", {}),
                "artform": (
                    ["disabled"] + ["random"] + ARTFORM,
                    {"default": "random"},
                ),
                "photo_type": (
                    ["disabled"] + ["random"] + PHOTO_TYPE,
                    {"default": "random"},
                ),
                "default_tags": (
                    ["disabled"] + ["random"] + DEFAULT_TAGS,
                    {"default": "random"},
                ),
                "roles": (["disabled"] + ["random"] + ROLES, {"default": "random"}),
                "hairstyles": (
                    ["disabled"] + ["random"] + HAIRSTYLES,
                    {"default": "random"},
                ),
                "additional_details": (
                    ["disabled"] + ["random"] + ADDITIONAL_DETAILS,
                    {"default": "random"},
                ),
                "photography_styles": (
                    ["disabled"] + ["random"] + PHOTOGRAPHY_STYLES,
                    {"default": "random"},
                ),
                "device": (["disabled"] + ["random"] + DEVICE, {"default": "random"}),
                "photographer": (
                    ["disabled"] + ["random"] + PHOTOGRAPHER,
                    {"default": "random"},
                ),
                "artist": (["disabled"] + ["random"] + ARTIST, {"default": "random"}),
                "digital_artform": (
                    ["disabled"] + ["random"] + DIGITAL_ARTFORM,
                    {"default": "random"},
                ),
                "place": (["disabled"] + ["random"] + PLACE, {"default": "random"}),
                "lighting": (
                    ["disabled"] + ["random"] + LIGHTING,
                    {"default": "random"},
                ),
            },
        }

    def split_and_choose(self, input_str):
        choices = [choice.strip() for choice in input_str.split(",")]
        return self.rng.choices(choices, k=1)[0]

    def get_choice(self, input_str, default_choices):
        if input_str.lower() == "disabled":
            return ""
        elif "," in input_str:
            return self.split_and_choose(input_str)
        elif input_str.lower() == "random":
            return self.rng.choices(default_choices, k=1)[0]
        else:
            return input_str

    def generate_prompt(self, **kwargs):
        seed = kwargs.get("seed", 0)
        if seed is not None:
            self.rng = random.Random(seed)
        components = []
        is_photographer = kwargs.get("artform", "").lower() == "photography" or (
            kwargs.get("artform", "").lower() == "random"
            and self.rng.choice([True, False])
        )

        if is_photographer:
            photo_type_choice = self.get_choice(
                kwargs.get("photo_type", ""), PHOTO_TYPE
            )
            if photo_type_choice:
                components.append(f"{photo_type_choice} of ")
        else:
            digital_artform_choice = self.get_choice(
                kwargs.get("digital_artform", ""), DIGITAL_ARTFORM
            )
            if digital_artform_choice:
                components.append(f"{digital_artform_choice} of ")

        lighting = kwargs.get("lighting", "").lower()
        if lighting == "random":
            selected_lighting = ", ".join(
                self.rng.sample(LIGHTING, self.rng.randint(2, 5))
            )  # assuming LIGHTING is a predefined list
            components.append(selected_lighting)
        elif lighting == "disabled":
            pass
        else:
            components.append(lighting)

        subject = kwargs.get("subject", "")
        default_tags = kwargs.get(
            "default_tags", "random"
        )  # default to "random" if not specified

        if not subject:
            if default_tags == "random":
                selected_subject = self.get_choice(
                    kwargs.get("default_tags", ""), DEFAULT_TAGS
                )
                components.append(selected_subject)
            elif default_tags == "disabled":
                pass
            else:
                components.append(default_tags)
        else:
            components.append(subject)

        params = [
            ("roles", ROLES),
            ("hairstyles", HAIRSTYLES),
            ("additional_details", ADDITIONAL_DETAILS),
            ("place", PLACE),
        ]
        components.extend(
            [self.get_choice(kwargs.get(param[0], ""), param[1]) for param in params]
        )

        if is_photographer:
            params = [
                ("photography_styles", PHOTOGRAPHY_STYLES),
                ("device", DEVICE),
                ("photographer", PHOTOGRAPHER),
            ]
            components.extend(
                [
                    self.get_choice(kwargs.get(param[0], ""), param[1])
                    for param in params
                ]
            )
            components[-2] = f"shot on {components[-2]}"
            components[-1] = f"photo by {components[-1]}"
        else:
            components.append(f"by {self.get_choice(kwargs.get('artist', ''), ARTIST)}")

        prompt = " ".join(components)
        prompt = re.sub(" +", " ", prompt)
        print(f"PromptGenerator Seed  : {seed}")
        print(f"PromptGenerator String: {prompt}")
        return (prompt.replace("of as", "of"), seed)


NODE_CLASS_MAPPINGS = {
    "PromptGenerator": PromptGenerator,
    # "CSVPromptGenerator": CSVPromptGenerator,
    # "CSL": CommaSeparatedList,
}

# Human readable names for the nodes
NODE_DISPLAY_NAME_MAPPINGS = {
    "PromptGenerator": "SDXL Auto Prompter",
    "CSL": "Comma Separated List",
}
